FROM openjdk:11

EXPOSE 8686

ADD ./target/volunteer-revert-service-0.0.1-SNAPSHOT.jar /volunteer-revert-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar", "/volunteer-revert-service-0.0.1-SNAPSHOT.jar"]
