eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8099

spring:
  application:
    name: "product-webapp"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true


