#Server port
server.port = 8888

#Git repo location.
spring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
spring.cloud.config.server.git.default-label=main

# Application name
spring.application.name=config-server

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

